### ISSUE TITLE
[0.0.68] Early Access and System requirements issue

### ISSUE THREAD

**Issue by Dave247** [phyziyx/steam2pcgw#3]
Ran the program on [Marauders](https://store.steampowered.com/app/1789480/Marauders/) and noticed a few output issues. This was tested using 0.0.68 version.

- As an early access title, the program put "Early Access" into the genre taxonomy field, although this is not a valid parameter in the template. Instead, the correct way to denote a game as early access is in the infobox release date row field with the parameter "EA" as stated in the editing guide.
https://www.pcgamingwiki.com/wiki/PCGamingWiki:Editing_guide/The_infobox#Release_date_rows

- I also noticed a few errors in the System requirements table output,
There is an added plain text output for the "Network" specification on the Steam page, due to their likely being no relevant PCGW specification to apply it to. This entire line can probably safely be ignored by the program, or potentially repurposed for some other use.
    - The program is unable to differentiate correctly when more than one CPU or GPU device is specified in Steam. Ideally, it would be smart enough to detect more than one has been specified, and split them up between the two fields correctly, as he current output simply output both onto the single "2" line.
    - Whenever a parameter is duplicated across both the minimum and recommended tables such is most common with the OS field, the best practices for the wiki is that only the minimum parapter is recorded, while the recommended parameter is left blank. Here, the program just copie both when it should know to ignore one in the event of a duplication.

Additionally, when a DirectX version is specified in the system, requirements box on Steam, aside from mirroring that to the PCGW system requirements table, it should also be safe to add to the API table under "direct3d versions" field.

**Comment by phyziyx** [comment]
Thanks for creating your first issue.

* Good catch!  This is an oversight and now has been resolved.
* System requirements require manual changes as hinted in the README.  Network line will now be stripped. I will look into resolving the duplication of details and detecting DirectX version at the earliest.

EDIT:  Discussion continued over at Discord.
