### ISSUE TITLE
Possible tips for 0.0.69

### ISSUE THREAD

**Issue by DandelionSprout** [phyziyx/steam2pcgw#4]
v0.0.68 allowed me to make https://www.pcgamingwiki.com/wiki/Rocket_Inc in a fairly impressive 3m42sec. The tool is certainly getting somewhere now. Though I have some ideas to shave off another half-minute from the timer:

- [x] The `|(min|rec)(CPU|GPU) =` rows are currently being rendered as e.g. `|minCPU    = |minCPU2    = 1 GHz`, which should be changed to e.g. `|minCPU    = 1 GHz` to prevent unnecessary newlines in those boxes.
- [x] Change `|OSfamily = Mac` to `|OSfamily = OS X`
- [x] Add `{{Infobox game/row/date|` for all OSs that a game has been released for, and not just for Windows. It'd be okay to use the same date for all OSs.
- [x] Remove `{{Infobox game/row/taxonomy/genres` values that PCGW consider to be invalid, e.g. `Casual`, `Indie`, and (from what I remember) `Free to Play`
- [x] Add an extra `\n` before `|steam cloud notes`
- [x] Change the `<!-- PAGE GENERATED BY PCGW2STEAM  -->` text to `<!-- PAGE GENERATED BY STEAM2PCGW  -->`
- [x] `|steam appid side` with DLC IDs seem to be rendered as: 
```
|steam appid side = 
1836570||gogcom id    = 
```
which should most likely be changed to:
```
|steam appid side = 1836570
|gogcom id    = 
```
- [x] (Optional:) Convert e.g. `|minGPU    = OpenGL 3.1 (...)` to `|minOGL    = 3.1`
- [x] (Optional:) A lot of the generated game descriptions are a bit too long and game-self-advertising to be relevant to PCGW, though I'm not eligible to judge whether they'd be against PCGW rules or not.
- [x] (Optional:) Remove one of the two newlines above `{{References}}`

**Comment by phyziyx** [comment]
So I should replace the `(min/rec)GPU` with `(min/rec)OGL` field.  Does this act as a replacement of GPU field or is that still needed, but should be left empty?

**Comment by DandelionSprout** [comment]
If I remember correctly, I suppose either way works equally well. If in doubt, you can take the latter approach.
